services:
  minio:
    depends_on:
    - AC-blockchain
    tty: true
    container_name: "minio_local"
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./Minio_folder:/data"
      - "./config.env:/etc/config.env"
    environment:
      MINIO_CONFIG_ENV_FILE: "/etc/config-dev.env"
    command: server /data --console-address ":9001"
  AC-blockchain:
    container_name: "AC-blockchain"
    image: ac-local-chain:latest
    build:
      context: src
      dockerfile: Dockerfile
    environment:
      NODE_ROLE: "publisher"
    ports:
      - "8000:8000"

