services:
  minio:
    tty: true
    container_name: "minio_local"
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./Minio_folder:/data"
      - "./config.env:/etc/config.env"
    environment:
      MINIO_CONFIG_ENV_FILE: "/etc/config.env"
    command: server /data --console-address ":9001"
  AC-blockchain:
    container_name: "AC-blockchain"
    depends_on:
      - minio
    image: ghcr.io/josephmartinelli/minio-blockchain:master
    ports:
      - "8000:8000"
    environment:
      NODE_ROLE: ""
      PORT: ""
      CHAIN_DIFFICULTY: ""


